branches:
  only:
  - master
  - "/^v.*$/"
language: python
notifications:
  email:
    on_success: change
    on_failure: always
  irc: chat.freenode.net#dedupe
matrix:
  include:
  - python: 3.7
  - python: 3.8
  - python: 3.9
  - python: 3.10
  - os: osx
    language: generic
    before_install:
      - brew update
      - brew upgrade python
      - python3 -m venv env
      - source env/bin/activate
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements-dev.txt
- pip install -e .
script:
- pytest --cov parserator
deploy:
  - provider: pypi
    skip_cleanup: true
    user: datamade.wheelbuilder
    on:
      tags: true
      condition: "$TRAVIS_OS_NAME = linux"
    distributions: "sdist bdist_wheel"
    password: $PYPIPASSWORD
env:
  global:
  - secure: ihuVvRbZ6SZuF1EJhz7qjS27HG/HJlviy6A3sb8mXfZSZPTh2aSJRsPFDl40/q9XOSYK5kQGNYC6cY6XKA48oFjjy47al3C5NA8yKzaqKDd6nSvZ04khpaLVtcLtX1zLRRenhR+8m8wOAudmz4BaeKOk1nCzOpTaPLnG3RYC0UM=
